___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [212]:
print("Версія NumPy: ", np.__version__)
print("Кофігураця: " )
np.__config__.show()

Версія NumPy:  1.16.5
Кофігураця: 
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaco

Створити вектор з 10 елементів, заповнений одиницями:

In [15]:
np.ones((1, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Створити вектор із значеннями від 0 до 10:

In [18]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [19]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [201]:
rand_array = np.random.randint(0, 10, (1,20))
print("Індекси нульових елементів: ", np.where(rand_array == 0)[1])


Індекси нульових елементів:  [19]


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [202]:
print("Середнє значення: ", rand_array.mean())
print("Медіана: ", np.median(rand_array))
print("Стандартне відхилення: ", rand_array.std())

Середнє значення:  5.85
Медіана:  7.0
Стандартне відхилення:  2.5743931323712004


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [203]:
rand_array1 = np.random.random((4,2))
rand_array2 = np.random.random((2,2))
rand_array3 = np.mat(rand_array1) * np.mat(rand_array2)
print(rand_array3)

[[0.65321669 1.04898866]
 [0.4925184  0.83406788]
 [0.45022031 0.72905509]
 [0.27345896 0.58275702]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [204]:
rand_array4 = rand_array3.reshape((1,8))
print("Мінімальне значення: ",rand_array4.min())
print("Максимальне значення: ", rand_array4.max())
rand_array4[rand_array4 == rand_array4.max()] = 0
print(rand_array4)


Мінімальне значення:  0.27345895676175497
Максимальне значення:  1.0489886583633832
[[0.65321669 0.         0.4925184  0.83406788 0.45022031 0.72905509
  0.27345896 0.58275702]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [205]:
np.corrcoef(rand_array3)

array([[ 1., -1., -1., -1.],
       [-1.,  1.,  1.,  1.],
       [-1.,  1.,  1.,  1.],
       [-1.,  1.,  1.,  1.]])

Дано матрицю. Знайти ранг матриці:

In [206]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [207]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [208]:
np.linalg.eig(a)

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
         -0.31386258+0.47450898j],
        [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
         -0.07049527-0.4090732j ],
        [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
          0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [209]:
import collections

a = np.random.randint(0,10,50)
b = collections.Counter(a.flatten())
max_value = max(dict(b).values())
max_number = [k for k, v in dict(b).items() if v == max_value][0]

print("Число ", max_number, ": ", max_value)

Число  3 :  7


Виведіть лише парні числа, що діляться на 5:

In [210]:
a = np.random.randint(0,10,50)
a = a[(a % 5 == 0) & (a % 2 == 0)]
print(a)
#тут тільки нуль і буде, якщо я не помиляюся
print("Unique values: ", np.unique(a))

[0 0 0 0 0 0]
Unique values:  [0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [211]:
A = np.array([[2, 5], [1, -10]])
B = np.array([1 ,3])
sl = np.linalg.solve(A, B)
print("x1 =", sl[0] )
print("x2 =", sl[1] )

x1 = 1.0
x2 = -0.2
